"""Шаблоны комментариев для активностей списания."""

from __future__ import annotations

# Без привязки к задаче — синхронизации, онбординг, дежурства и т.п.
STATIC_COMMENTS: dict[str, str] = {
    "an-onboarding": "Передача знаний",
    "an-sync": "Синхронизация с командой",
    "an-ws": "Рабочая сессия с командой",
    "an-demo": "Демонстрация результатов",
    "an-defect-triage": "Разбор и уточнение дефектов",
    "an-other": "Аналитическая работа",
    "ar-consult": "Консультация команды",
    "ar-guild": "Architecture guild / комитет",
    "ar-other": "Архитектурная работа",
    "dev-onboarding": "Помощь коллегам",
    "dev-standup": "Daily / синхронизация",
    "dev-review": "Code review",
    "dev-self-review": "Доработка по code review",
    "dev-planning": "Планирование / estimation",
    "dev-local-env": "Настройка локального окружения",
    "dev-other": "Разработка",
    "qa-sync": "Синхронизация с командой",
    "qa-other": "Тестирование",
    "qaa-onboarding": "Помощь коллегам",
    "qaa-other": "Автоматизация тестирования",
    "qal-other": "Нагрузочное тестирование",
    "do-oncall": "On-call / дежурство",
    "do-support": "Поддержка команд",
    "do-other": "DevOps",
    "pm-onboarding": "Онбординг команды",
    "pm-status": "Status meeting",
    "pm-other": "Работа РГР",
}

# Расширенные шаблоны с {feature} — приоритетнее role-паттерна.
COMMENT_TEMPLATES: dict[str, str] = {
    # Аналитик
    "an-spec-dev": "Разработка ТЗ для функционала «{feature}»",
    "an-spec-update": "Актуализация ТЗ по «{feature}»",
    "an-spec-ect": "Взаимодействие с ЕЦТ по приёмке «{feature}»",
    "an-spec-fix-agree": "Корректировка ТЗ по согласованию «{feature}»",
    "an-brief-fix": "Корректировка брифа для «{feature}»",
    "an-spec-fix-review": "Корректировки ТЗ по ревью «{feature}»",
    "an-brief-write": "Написание брифа по «{feature}»",
    "an-req-gather": "Сбор и анализ требований для «{feature}»",
    "an-req-interview": "Интервью по требованиям «{feature}»",
    "an-as-is": "Описание AS-IS для «{feature}»",
    "an-to-be": "Описание TO-BE для «{feature}»",
    "an-user-story": "Декомпозиция «{feature}» на user story",
    "an-accept-crit": "Критерии приёмки для «{feature}»",
    "an-use-case": "Use case / сценарии для «{feature}»",
    "an-bpmn": "Моделирование процессов «{feature}»",
    "an-prototype": "Прототипирование «{feature}»",
    "an-mockup": "Макеты для согласования «{feature}»",
    "an-data-model": "Модель данных для «{feature}»",
    "an-api-spec": "Описание API для «{feature}»",
    "an-integration": "Проработка интеграций «{feature}»",
    "an-gap": "Gap-анализ «{feature}»",
    "an-impact": "Impact-анализ «{feature}»",
    "an-risk": "Анализ рисков «{feature}»",
    "an-feasibility": "Оценка feasibility «{feature}»",
    "an-estimate": "Оценка трудозатрат «{feature}»",
    "an-approval": "Согласование «{feature}» с бизнесом",
    "an-legal": "Согласование «{feature}» с юристами / compliance",
    "an-security-req": "Требования ИБ для «{feature}»",
    "an-uat-support": "Сопровождение UAT «{feature}»",
    "an-release-notes": "Release notes по «{feature}»",
    "an-doc": "Проектная документация «{feature}»",
    "an-confluence": "Актуализация Confluence по «{feature}»",
    "an-research": "Исследование / R&D по «{feature}»",
    # Архитектор
    "ar-solution": "Проектирование решения «{feature}»",
    "ar-high-level": "High-level design «{feature}»",
    "ar-low-level": "Low-level design «{feature}»",
    "ar-adr": "ADR по «{feature}»",
    "ar-review": "Architecture review «{feature}»",
    "ar-code-review": "Архитектурный code review «{feature}»",
    "ar-integration": "Проектирование интеграций «{feature}»",
    "ar-api": "Проектирование API «{feature}»",
    "ar-data": "Проектирование данных «{feature}»",
    "ar-security": "Архитектура безопасности «{feature}»",
    "ar-performance": "Проектирование производительности «{feature}»",
    "ar-scalability": "Масштабируемость / отказоустойчивость «{feature}»",
    "ar-poc": "PoC / прототип «{feature}»",
    "ar-spike": "Spike / исследование «{feature}»",
    "ar-tech-debt": "Анализ техдолга «{feature}»",
    "ar-refactor-plan": "План рефакторинга «{feature}»",
    "ar-standards": "Стандарты и guidelines для «{feature}»",
    "ar-patterns": "Выбор паттернов / технологий «{feature}»",
    "ar-diagram": "Диаграммы (C4, sequence) «{feature}»",
    "ar-vendor": "Оценка вендоров для «{feature}»",
    "ar-audit": "Технический аудит «{feature}»",
    "ar-incident": "Разбор инцидента (архитектура) «{feature}»",
    # Разработчик
    "dev-coding": "Разработка «{feature}»",
    "dev-feature": "Реализация функционала «{feature}»",
    "dev-bugfix": "Исправление дефекта по «{feature}»",
    "dev-hotfix": "Hotfix по «{feature}»",
    "dev-refactor": "Рефакторинг «{feature}»",
    "dev-merge": "Merge / разрешение конфликтов «{feature}»",
    "dev-unit-test": "Unit-тесты «{feature}»",
    "dev-integration-test": "Integration-тесты «{feature}»",
    "dev-debug": "Отладка «{feature}»",
    "dev-spike": "Spike / исследование «{feature}»",
    "dev-poc": "PoC «{feature}»",
    "dev-api": "Разработка API «{feature}»",
    "dev-fe": "Frontend-разработка «{feature}»",
    "dev-be": "Backend-разработка «{feature}»",
    "dev-mobile": "Mobile-разработка «{feature}»",
    "dev-db": "Работа с БД / миграции «{feature}»",
    "dev-config": "Конфигурация / feature flags «{feature}»",
    "dev-build-fix": "Починка сборки «{feature}»",
    "dev-perf": "Оптимизация производительности «{feature}»",
    "dev-security": "Исправления по ИБ «{feature}»",
    "dev-tech-debt": "Закрытие техдолга «{feature}»",
    "dev-doc": "Техническая документация «{feature}»",
    "dev-demo": "Подготовка демо «{feature}»",
    "dev-deploy-support": "Сопровождение выкладки «{feature}»",
    "dev-incident": "Разбор инцидента (разработка) «{feature}»",
    # QA
    "qa-manual": "Ручное тестирование «{feature}»",
    "qa-smoke": "Smoke-тестирование «{feature}»",
    "qa-regression": "Регрессионное тестирование «{feature}»",
    "qa-exploratory": "Exploratory testing «{feature}»",
    "qa-test-case": "Написание тест-кейсов «{feature}»",
    "qa-test-plan": "Тест-план «{feature}»",
    "qa-checklist": "Чек-листы «{feature}»",
    "qa-uat": "UAT / приёмочное тестирование «{feature}»",
    "qa-retest": "Retest «{feature}»",
    "qa-bug-report": "Оформление багов по «{feature}»",
    "qa-bug-verify": "Верификация исправлений «{feature}»",
    "qa-data-prep": "Подготовка тестовых данных «{feature}»",
    "qa-env": "Подготовка тестового окружения «{feature}»",
    "qa-integration": "Интеграционное тестирование «{feature}»",
    "qa-api": "Тестирование API «{feature}»",
    "qa-ui": "UI / UX проверка «{feature}»",
    "qa-mobile": "Тестирование mobile «{feature}»",
    "qa-cross": "Кроссбраузерное тестирование «{feature}»",
    "qa-accessibility": "Accessibility-тестирование «{feature}»",
    "qa-localization": "Локализация / i18n «{feature}»",
    "qa-review-req": "Review требований / ТЗ «{feature}»",
    "qa-metrics": "Метрики качества «{feature}»",
    "qa-demo": "Демо результатов тестирования «{feature}»",
    # QA Автоматизация
    "qaa-auto-write": "Разработка автотестов для «{feature}»",
    "qaa-auto-run": "Запуск автотестов «{feature}»",
    "qaa-auto-fix": "Починка автотестов «{feature}»",
    "qaa-auto-refactor": "Рефакторинг автотестов «{feature}»",
    "qaa-framework": "Развитие test framework «{feature}»",
    "qaa-ci": "Интеграция автотестов в CI «{feature}»",
    "qaa-report": "Allure / отчёты автотестов «{feature}»",
    "qaa-api-auto": "API-автотесты «{feature}»",
    "qaa-ui-auto": "UI-автотесты «{feature}»",
    "qaa-mobile-auto": "Mobile-автотесты «{feature}»",
    "qaa-contract": "Contract testing «{feature}»",
    "qaa-mock": "Mock / stub сервисов «{feature}»",
    "qaa-data": "Генерация тестовых данных «{feature}»",
    "qaa-review": "Review автотестов «{feature}»",
    "qaa-spike": "Spike / выбор инструмента «{feature}»",
    "qaa-doc": "Документация по автотестам «{feature}»",
    # QA Нагрузка
    "qal-script": "Разработка нагрузочных скриптов для функционала «{feature}»",
    "qal-run": "Проведение нагрузочного тестирования «{feature}»",
    "qal-analysis": "Анализ результатов НТ «{feature}»",
    "qal-plan": "План нагрузочного тестирования «{feature}»",
    "qal-profile": "Профилирование / bottleneck «{feature}»",
    "qal-stress": "Stress-тестирование «{feature}»",
    "qal-stability": "Stability / soak-тесты «{feature}»",
    "qal-spike": "Spike-тестирование «{feature}»",
    "qal-env": "Подготовка стенда НТ «{feature}»",
    "qal-monitor": "Мониторинг во время НТ «{feature}»",
    "qal-report": "Отчёт по нагрузке «{feature}»",
    "qal-tuning": "Рекомендации по tuning «{feature}»",
    "qal-regression-perf": "Performance regression «{feature}»",
    # DevOps
    "do-deploy": "Деплой / выкладка «{feature}»",
    "do-ci": "CI pipeline «{feature}»",
    "do-cd": "CD pipeline «{feature}»",
    "do-infra": "Инфраструктура / IaC «{feature}»",
    "do-k8s": "Kubernetes «{feature}»",
    "do-docker": "Docker / контейнеры «{feature}»",
    "do-monitoring": "Мониторинг / alerting «{feature}»",
    "do-logging": "Логирование / ELK «{feature}»",
    "do-backup": "Backup / restore «{feature}»",
    "do-security": "Hardening «{feature}»",
    "do-secrets": "Secrets / certificates «{feature}»",
    "do-network": "Сеть / firewall «{feature}»",
    "do-db-ops": "DBA / сопровождение БД «{feature}»",
    "do-incident": "Incident response «{feature}»",
    "do-capacity": "Capacity planning «{feature}»",
    "do-cost": "Cost optimization «{feature}»",
    "do-automation": "Автоматизация «{feature}»",
    "do-doc": "Runbooks «{feature}»",
    "do-migration": "Миграция окружений «{feature}»",
    # РГР
    "pm-planning": "Планирование релиза / спринта «{feature}»",
    "pm-backlog": "Grooming backlog «{feature}»",
    "pm-roadmap": "Roadmap «{feature}»",
    "pm-report": "Отчётность / метрики «{feature}»",
    "pm-risk": "Управление рисками «{feature}»",
    "pm-budget": "Бюджет / ресурсы «{feature}»",
    "pm-stakeholder": "Коммуникация со стейкхолдерами «{feature}»",
    "pm-escalation": "Эскалации «{feature}»",
    "pm-contract": "Взаимодействие с подрядчиками «{feature}»",
    "pm-process": "Процессы / улучшения «{feature}»",
    "pm-jira": "Администрирование Jira / TFS «{feature}»",
    "pm-release": "Координация релиза «{feature}»",
    "pm-uat-coord": "Координация UAT «{feature}»",
    "pm-change": "Change management «{feature}»",
}

ROLE_COMMENT_PATTERNS: dict[str, str] = {
    "analyst": "{label} по функционалу «{feature}»",
    "architect": "{label} для «{feature}»",
    "developer": "{label} в рамках «{feature}»",
    "qa": "{label} функционала «{feature}»",
    "qa-auto": "{label} для «{feature}»",
    "qa-load": "{label} функционала «{feature}»",
    "devops": "{label} по «{feature}»",
    "pm": "{label} по инициативе «{feature}»",
}


def comment_template_for(activity_id: str, label: str, role_id: str) -> str:
    static = STATIC_COMMENTS.get(activity_id)
    if static:
        return static

    explicit = COMMENT_TEMPLATES.get(activity_id)
    if explicit:
        return explicit

    lower = label.casefold()
    if " / " in label:
        _, _, tail = label.partition(" / ")
        tail = tail.strip()
        if tail and any(token in lower for token in ("онбординг", "передача знаний", "обучение", "помощь")):
            return tail[0].upper() + tail[1:] if tail else label

    role_pattern = ROLE_COMMENT_PATTERNS.get(role_id)
    if role_pattern:
        return role_pattern.replace("{label}", label)

    return f"{label} — «{{feature}}»"
