"""Справочник активностей для списания времени по ролям."""

from app.schemas import ActivityOut

ACTIVITIES: list[ActivityOut] = [
    # ── Аналитик ──────────────────────────────────────────────────────────
    ActivityOut(id="an-spec-dev", label="Разработка ТЗ", role_id="analyst"),
    ActivityOut(id="an-spec-update", label="Актуализация ТЗ", role_id="analyst"),
    ActivityOut(id="an-spec-ect", label="Взаимодействие с ЕЦТ по приемке", role_id="analyst"),
    ActivityOut(id="an-spec-fix-agree", label="Корректировка ТЗ по согласованию", role_id="analyst"),
    ActivityOut(id="an-brief-fix", label="Корректировка брифа для согласования", role_id="analyst"),
    ActivityOut(id="an-spec-fix-review", label="Корректировки ТЗ по ревью", role_id="analyst"),
    ActivityOut(id="an-brief-write", label="Написание брифа", role_id="analyst"),
    ActivityOut(id="an-req-gather", label="Сбор и анализ требований", role_id="analyst"),
    ActivityOut(id="an-req-interview", label="Интервью с заказчиком / стейкхолдерами", role_id="analyst"),
    ActivityOut(id="an-as-is", label="Описание AS-IS / текущего процесса", role_id="analyst"),
    ActivityOut(id="an-to-be", label="Описание TO-BE / целевого процесса", role_id="analyst"),
    ActivityOut(id="an-user-story", label="Декомпозиция на user story", role_id="analyst"),
    ActivityOut(id="an-accept-crit", label="Разработка критериев приёмки", role_id="analyst"),
    ActivityOut(id="an-use-case", label="Описание use case / сценариев", role_id="analyst"),
    ActivityOut(id="an-bpmn", label="Моделирование BPMN / процессов", role_id="analyst"),
    ActivityOut(id="an-prototype", label="Прототипирование / wireframes", role_id="analyst"),
    ActivityOut(id="an-mockup", label="Подготовка макетов для согласования", role_id="analyst"),
    ActivityOut(id="an-data-model", label="Описание модели данных", role_id="analyst"),
    ActivityOut(id="an-api-spec", label="Описание API / контрактов", role_id="analyst"),
    ActivityOut(id="an-integration", label="Проработка интеграций", role_id="analyst"),
    ActivityOut(id="an-gap", label="Gap-анализ", role_id="analyst"),
    ActivityOut(id="an-impact", label="Impact-анализ", role_id="analyst"),
    ActivityOut(id="an-risk", label="Анализ рисков", role_id="analyst"),
    ActivityOut(id="an-feasibility", label="Оценка feasibility", role_id="analyst"),
    ActivityOut(id="an-estimate", label="Оценка трудозатрат", role_id="analyst"),
    ActivityOut(id="an-demo", label="Подготовка и проведение демо", role_id="analyst"),
    ActivityOut(id="an-ws", label="Воркшоп / рабочая сессия", role_id="analyst"),
    ActivityOut(id="an-sync", label="Синхронизация с командой / стримом", role_id="analyst"),
    ActivityOut(id="an-approval", label="Согласование с бизнесом", role_id="analyst"),
    ActivityOut(id="an-legal", label="Согласование с юристами / compliance", role_id="analyst"),
    ActivityOut(id="an-security-req", label="Проработка требований ИБ", role_id="analyst"),
    ActivityOut(id="an-uat-support", label="Сопровождение UAT", role_id="analyst"),
    ActivityOut(id="an-defect-triage", label="Разбор дефектов / уточнение", role_id="analyst"),
    ActivityOut(id="an-release-notes", label="Release notes / описание релиза", role_id="analyst"),
    ActivityOut(id="an-doc", label="Ведение проектной документации", role_id="analyst"),
    ActivityOut(id="an-confluence", label="Актуализация Confluence / Wiki", role_id="analyst"),
    ActivityOut(id="an-onboarding", label="Онбординг / передача знаний", role_id="analyst"),
    ActivityOut(id="an-research", label="Исследование / R&D", role_id="analyst"),
    ActivityOut(id="an-other", label="Прочая аналитическая работа", role_id="analyst"),
    # ── Архитектор ────────────────────────────────────────────────────────
    ActivityOut(id="ar-solution", label="Проектирование решения", role_id="architect"),
    ActivityOut(id="ar-high-level", label="High-level design", role_id="architect"),
    ActivityOut(id="ar-low-level", label="Low-level design", role_id="architect"),
    ActivityOut(id="ar-adr", label="Architecture Decision Record (ADR)", role_id="architect"),
    ActivityOut(id="ar-review", label="Architecture review", role_id="architect"),
    ActivityOut(id="ar-code-review", label="Code review (архитектурный)", role_id="architect"),
    ActivityOut(id="ar-integration", label="Проектирование интеграций", role_id="architect"),
    ActivityOut(id="ar-api", label="Проектирование API", role_id="architect"),
    ActivityOut(id="ar-data", label="Проектирование данных / хранилищ", role_id="architect"),
    ActivityOut(id="ar-security", label="Архитектура безопасности", role_id="architect"),
    ActivityOut(id="ar-performance", label="Проектирование производительности", role_id="architect"),
    ActivityOut(id="ar-scalability", label="Масштабируемость / отказоустойчивость", role_id="architect"),
    ActivityOut(id="ar-poc", label="PoC / технический прототип", role_id="architect"),
    ActivityOut(id="ar-spike", label="Spike / техническое исследование", role_id="architect"),
    ActivityOut(id="ar-tech-debt", label="Анализ технического долга", role_id="architect"),
    ActivityOut(id="ar-refactor-plan", label="План рефакторинга / миграции", role_id="architect"),
    ActivityOut(id="ar-standards", label="Стандарты и guidelines", role_id="architect"),
    ActivityOut(id="ar-patterns", label="Выбор паттернов / технологий", role_id="architect"),
    ActivityOut(id="ar-diagram", label="Диаграммы (C4, sequence, deployment)", role_id="architect"),
    ActivityOut(id="ar-consult", label="Консультация команды", role_id="architect"),
    ActivityOut(id="ar-guild", label="Architecture guild / комитет", role_id="architect"),
    ActivityOut(id="ar-vendor", label="Оценка вендоров / продуктов", role_id="architect"),
    ActivityOut(id="ar-audit", label="Технический аудит", role_id="architect"),
    ActivityOut(id="ar-incident", label="Разбор инцидента (архитектура)", role_id="architect"),
    ActivityOut(id="ar-other", label="Прочая архитектурная работа", role_id="architect"),
    # ── Разработчик ───────────────────────────────────────────────────────
    ActivityOut(id="dev-coding", label="Разработка", role_id="developer"),
    ActivityOut(id="dev-feature", label="Реализация фичи", role_id="developer"),
    ActivityOut(id="dev-bugfix", label="Исправление дефекта", role_id="developer"),
    ActivityOut(id="dev-hotfix", label="Hotfix / срочное исправление", role_id="developer"),
    ActivityOut(id="dev-refactor", label="Рефакторинг", role_id="developer"),
    ActivityOut(id="dev-review", label="Code review", role_id="developer"),
    ActivityOut(id="dev-self-review", label="Self-review / доработка по review", role_id="developer"),
    ActivityOut(id="dev-merge", label="Merge / разрешение конфликтов", role_id="developer"),
    ActivityOut(id="dev-unit-test", label="Unit-тесты", role_id="developer"),
    ActivityOut(id="dev-integration-test", label="Integration-тесты", role_id="developer"),
    ActivityOut(id="dev-debug", label="Отладка / troubleshooting", role_id="developer"),
    ActivityOut(id="dev-spike", label="Spike / исследование", role_id="developer"),
    ActivityOut(id="dev-poc", label="PoC", role_id="developer"),
    ActivityOut(id="dev-api", label="Разработка API", role_id="developer"),
    ActivityOut(id="dev-fe", label="Frontend-разработка", role_id="developer"),
    ActivityOut(id="dev-be", label="Backend-разработка", role_id="developer"),
    ActivityOut(id="dev-mobile", label="Mobile-разработка", role_id="developer"),
    ActivityOut(id="dev-db", label="Работа с БД / миграции", role_id="developer"),
    ActivityOut(id="dev-config", label="Конфигурация / feature flags", role_id="developer"),
    ActivityOut(id="dev-local-env", label="Настройка локального окружения", role_id="developer"),
    ActivityOut(id="dev-build-fix", label="Починка сборки", role_id="developer"),
    ActivityOut(id="dev-perf", label="Оптимизация производительности", role_id="developer"),
    ActivityOut(id="dev-security", label="Исправления по ИБ", role_id="developer"),
    ActivityOut(id="dev-tech-debt", label="Закрытие техдолга", role_id="developer"),
    ActivityOut(id="dev-doc", label="Техническая документация", role_id="developer"),
    ActivityOut(id="dev-onboarding", label="Онбординг / помощь коллегам", role_id="developer"),
    ActivityOut(id="dev-standup", label="Daily / синхронизация", role_id="developer"),
    ActivityOut(id="dev-planning", label="Планирование / estimation", role_id="developer"),
    ActivityOut(id="dev-demo", label="Подготовка демо", role_id="developer"),
    ActivityOut(id="dev-deploy-support", label="Сопровождение выкладки", role_id="developer"),
    ActivityOut(id="dev-incident", label="Разбор инцидента (разработка)", role_id="developer"),
    ActivityOut(id="dev-other", label="Прочая разработка", role_id="developer"),
    # ── QA ────────────────────────────────────────────────────────────────
    ActivityOut(id="qa-manual", label="Ручное тестирование", role_id="qa"),
    ActivityOut(id="qa-smoke", label="Smoke-тестирование", role_id="qa"),
    ActivityOut(id="qa-regression", label="Регрессионное тестирование", role_id="qa"),
    ActivityOut(id="qa-exploratory", label="Exploratory testing", role_id="qa"),
    ActivityOut(id="qa-test-case", label="Написание тест-кейсов", role_id="qa"),
    ActivityOut(id="qa-test-plan", label="Тест-план", role_id="qa"),
    ActivityOut(id="qa-checklist", label="Чек-листы", role_id="qa"),
    ActivityOut(id="qa-uat", label="UAT / приёмочное тестирование", role_id="qa"),
    ActivityOut(id="qa-retest", label="Retest / перепроверка", role_id="qa"),
    ActivityOut(id="qa-bug-report", label="Оформление багов", role_id="qa"),
    ActivityOut(id="qa-bug-verify", label="Верификация исправлений", role_id="qa"),
    ActivityOut(id="qa-data-prep", label="Подготовка тестовых данных", role_id="qa"),
    ActivityOut(id="qa-env", label="Подготовка тестового окружения", role_id="qa"),
    ActivityOut(id="qa-integration", label="Интеграционное тестирование", role_id="qa"),
    ActivityOut(id="qa-api", label="Тестирование API", role_id="qa"),
    ActivityOut(id="qa-ui", label="UI / UX проверка", role_id="qa"),
    ActivityOut(id="qa-mobile", label="Тестирование mobile", role_id="qa"),
    ActivityOut(id="qa-cross", label="Кроссбраузерное / кроссплатформенное", role_id="qa"),
    ActivityOut(id="qa-accessibility", label="Accessibility-тестирование", role_id="qa"),
    ActivityOut(id="qa-localization", label="Локализация / i18n", role_id="qa"),
    ActivityOut(id="qa-review-req", label="Review требований / ТЗ", role_id="qa"),
    ActivityOut(id="qa-metrics", label="Метрики качества / отчётность", role_id="qa"),
    ActivityOut(id="qa-demo", label="Демо / показ результатов", role_id="qa"),
    ActivityOut(id="qa-sync", label="Синхронизация с командой", role_id="qa"),
    ActivityOut(id="qa-other", label="Прочее тестирование", role_id="qa"),
    # ── QA Автоматизация ──────────────────────────────────────────────────
    ActivityOut(id="qaa-auto-write", label="Написание автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-auto-run", label="Запуск автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-auto-fix", label="Починка автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-auto-refactor", label="Рефакторинг автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-framework", label="Развитие test framework", role_id="qa-auto"),
    ActivityOut(id="qaa-ci", label="Интеграция автотестов в CI", role_id="qa-auto"),
    ActivityOut(id="qaa-report", label="Allure / отчёты автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-api-auto", label="API-автотесты", role_id="qa-auto"),
    ActivityOut(id="qaa-ui-auto", label="UI-автотесты", role_id="qa-auto"),
    ActivityOut(id="qaa-mobile-auto", label="Mobile-автотесты", role_id="qa-auto"),
    ActivityOut(id="qaa-contract", label="Contract testing", role_id="qa-auto"),
    ActivityOut(id="qaa-mock", label="Mock / stub сервисов", role_id="qa-auto"),
    ActivityOut(id="qaa-data", label="Генерация тестовых данных", role_id="qa-auto"),
    ActivityOut(id="qaa-review", label="Review автотестов", role_id="qa-auto"),
    ActivityOut(id="qaa-spike", label="Spike / выбор инструмента", role_id="qa-auto"),
    ActivityOut(id="qaa-doc", label="Документация по автотестам", role_id="qa-auto"),
    ActivityOut(id="qaa-onboarding", label="Онбординг / обучение", role_id="qa-auto"),
    ActivityOut(id="qaa-other", label="Прочая автоматизация", role_id="qa-auto"),
    # ── QA Нагрузка ───────────────────────────────────────────────────────
    ActivityOut(id="qal-script", label="Разработка нагрузочных скриптов", role_id="qa-load"),
    ActivityOut(id="qal-run", label="Проведение нагрузочных тестов", role_id="qa-load"),
    ActivityOut(id="qal-analysis", label="Анализ результатов НТ", role_id="qa-load"),
    ActivityOut(id="qal-plan", label="План нагрузочного тестирования", role_id="qa-load"),
    ActivityOut(id="qal-profile", label="Профилирование / bottleneck", role_id="qa-load"),
    ActivityOut(id="qal-stress", label="Stress-тестирование", role_id="qa-load"),
    ActivityOut(id="qal-stability", label="Stability / soak-тесты", role_id="qa-load"),
    ActivityOut(id="qal-spike", label="Spike-тестирование", role_id="qa-load"),
    ActivityOut(id="qal-env", label="Подготовка стенда НТ", role_id="qa-load"),
    ActivityOut(id="qal-monitor", label="Мониторинг во время НТ", role_id="qa-load"),
    ActivityOut(id="qal-report", label="Отчёт по нагрузке", role_id="qa-load"),
    ActivityOut(id="qal-tuning", label="Рекомендации по tuning", role_id="qa-load"),
    ActivityOut(id="qal-regression-perf", label="Performance regression", role_id="qa-load"),
    ActivityOut(id="qal-other", label="Прочее нагрузочное тестирование", role_id="qa-load"),
    # ── DevOps ────────────────────────────────────────────────────────────
    ActivityOut(id="do-deploy", label="Деплой / выкладка", role_id="devops"),
    ActivityOut(id="do-ci", label="CI pipeline", role_id="devops"),
    ActivityOut(id="do-cd", label="CD pipeline", role_id="devops"),
    ActivityOut(id="do-infra", label="Инфраструктура / IaC", role_id="devops"),
    ActivityOut(id="do-k8s", label="Kubernetes / оркестрация", role_id="devops"),
    ActivityOut(id="do-docker", label="Docker / контейнеры", role_id="devops"),
    ActivityOut(id="do-monitoring", label="Мониторинг / alerting", role_id="devops"),
    ActivityOut(id="do-logging", label="Логирование / ELK", role_id="devops"),
    ActivityOut(id="do-backup", label="Backup / restore", role_id="devops"),
    ActivityOut(id="do-security", label="Hardening / ИБ инфраструктуры", role_id="devops"),
    ActivityOut(id="do-secrets", label="Secrets / certificates", role_id="devops"),
    ActivityOut(id="do-network", label="Сеть / firewall / DNS", role_id="devops"),
    ActivityOut(id="do-db-ops", label="DBA / сопровождение БД", role_id="devops"),
    ActivityOut(id="do-incident", label="Incident response", role_id="devops"),
    ActivityOut(id="do-oncall", label="On-call / дежурство", role_id="devops"),
    ActivityOut(id="do-capacity", label="Capacity planning", role_id="devops"),
    ActivityOut(id="do-cost", label="Cost optimization", role_id="devops"),
    ActivityOut(id="do-automation", label="Автоматизация рутины", role_id="devops"),
    ActivityOut(id="do-support", label="Поддержка команд", role_id="devops"),
    ActivityOut(id="do-doc", label="Runbooks / документация", role_id="devops"),
    ActivityOut(id="do-migration", label="Миграция окружений", role_id="devops"),
    ActivityOut(id="do-other", label="Прочий DevOps", role_id="devops"),
    # ── РГР ───────────────────────────────────────────────────────────────
    ActivityOut(id="pm-planning", label="Планирование релиза / спринта", role_id="pm"),
    ActivityOut(id="pm-backlog", label="Grooming / приоритизация backlog", role_id="pm"),
    ActivityOut(id="pm-roadmap", label="Roadmap / портфель", role_id="pm"),
    ActivityOut(id="pm-status", label="Status / steering committee", role_id="pm"),
    ActivityOut(id="pm-report", label="Отчётность / метрики", role_id="pm"),
    ActivityOut(id="pm-risk", label="Управление рисками", role_id="pm"),
    ActivityOut(id="pm-budget", label="Бюджет / ресурсы", role_id="pm"),
    ActivityOut(id="pm-stakeholder", label="Коммуникация со стейкхолдерами", role_id="pm"),
    ActivityOut(id="pm-escalation", label="Эскалации", role_id="pm"),
    ActivityOut(id="pm-contract", label="Взаимодействие с подрядчиками", role_id="pm"),
    ActivityOut(id="pm-onboarding", label="Онбординг команды", role_id="pm"),
    ActivityOut(id="pm-process", label="Процессы / улучшения", role_id="pm"),
    ActivityOut(id="pm-jira", label="Администрирование Jira / TFS", role_id="pm"),
    ActivityOut(id="pm-release", label="Координация релиза", role_id="pm"),
    ActivityOut(id="pm-uat-coord", label="Координация UAT / приёмки", role_id="pm"),
    ActivityOut(id="pm-change", label="Change management", role_id="pm"),
    ActivityOut(id="pm-other", label="Прочая РГР-работа", role_id="pm"),
]
